main: de.timesnake.basic.proxy.core.main.BasicProxy
version: 1.3
name: basic-proxy
author: timesnake
softdepend: [ database-proxy ]

commands:
  permission:
    aliases:
      - perm
      - perms

  alias:


  work:

  jail:
  ban:
  tempban:
    aliases:
      - tmpban

  kick:
  tempmute:
  unmute:
  unban:
  pardon:

  support:
  ticket:
  tickets:

  supportmsg:
    aliases:
      - supportmessages
      - supportmessage
      - supportmsgs

  netmsg:
    aliases:
      - netmessages
      - networkmsg
      - networkmessages
      - networkmessage
      - netmsgs

  shutdown:

  autoshutdown:

  permcheck:

  rule:
    aliases:
      - rules
      - regel
      - regeln

  pid:

  kickall:

  dtmp:
    aliases:
      - delete_tmp
  cleanup_servers:

  dg:
    aliases:
      - dgroup
      - displaygroup

  build:

  network:

  logger:
    aliases:
      - log

  uuid:

  code:

  game:
     