main: de.timesnake.basic.proxy.core.main.BasicProxy
version: 1.3
name: basic-proxy
author: Mn
softdepend: [ database-proxy ]

commands:
  perm:
  permission:
  alias:
  al:
  work:
  netban:
  nettempban:
  nettmpban:
  netkick:
  netmute:
  nettempmute:
  netunmute:
  netunban:
  netpardon:
  netjail:
  jail:

  ban:
  tempban:
  tmpban:
  kick:
  mute:
  tempmute:
  unmute:
  unban:
  pardon:

  support:
  ticket:
  tickets:
  supportmessages:
  supportmessage:
  supportmsg:
  supportmsgs:

  netmessages:

  channelmsg:
  channelmsgs:
  channelmessages:
  channelmessage:

  shutdown:
  autoshutdown:

  databasemsg:
  databasemsgs:
  databasemessage:
  databasemesseges:

  permcheck:

  rule:
  rules:
  regel:
  regeln:

  pid:

  kickall:

  dtmp:
  delete_tmp:
  cleanup_servers:

  dgroup:
  displaygroup:
  dg:

  build:

  network:

  log:
  logger:

  uuid:

  code:

  game:
     